### ISSUE TITLE
Plans for support for Pathfinder 1 system?

### ISSUE THREAD

**Issue by ArdonDaros** [jessev14/environment-interaction#1]
Looks amazing! Do you have any plans to support Pathfinder 1 system?

**Comment by jessev14** [comment]
I unfortunately don't have the time to extend support to systems on my own right now. I'd be happy to merge PRs or would at least need some information about the system to make developing easier.
That kind of information would include:

- Item types analogous to what I currently have set up for dnd5e
- Interaction types that would be sensible for the system (weapon rolls, skill checks/saves, etc.) and how they are implemented in the system.

Even if you don't have all this info, feel free to reach out on Discord (`enso#0361`) and we can discuss further.
